### ISSUE TITLE
Questengine. Quests works only in 50% cases.

### ISSUE THREAD

**Issue by jfaubert087** [Daenks/Meridian59_103#1088]
I'm not really sure about that, but I've just downloaded the whole repo, compiled it and ran a fresh server. I created two accounts, admin and user and after that I tried to complete Riija sword quest and it didn't worked for me.

Diggie's Recomendations from IRC (and keen's and Delerium's):
1. send o 0 recreateall
2. Do Garbage.
3. Do Save.
**P.S.** Delerium also mention that this might help: *`send o <questNPC#> TryAddToQuestEngine`*.

This works only in few cases, and after that the quest system doesn't work again.
I don't see any good solution at this moment, so if you find any, please post them here.

— Joseph

**Comment by skittles1** [comment]
The quests you are trying to get have less than 100% scheduling chance. Read the files.
