### ISSUE TITLE
Healing Rods / general concerns

### ISSUE THREAD

**Issue by Yeshir** [Daenks/Meridian59_103#435]
As far as I experienced it by now, healing rods are far to strong in PVP. Especially when fighting against a mage build.

Being able to carry ~150 bonus HP with you as a PF is rediculous. Mages can run out of steam pretty fast due to their limitation by mana. That for itself is okay. But if you need more or less your whole mana pool to bring down a PF to ~0 while he can heal up again close to full hp in no time while you cant do anything beside running from his arrows - something is wrong.

This leads to my next concern. You make quite a lot of deep going decisions and alterations here without having them carefully tested. Some might sound good "on paper" but can (and do) seriously mess things up. You have to be more careful with your changes which deal with pvp balance. Please. Dont get to excited with the possibilities you have on 103 and take it more slow and calm.

**Comment by skittles1** [comment]
Heal rods have a 500ms delay now (1 sec default but we're trialling 500ms) so this problem is kinda fixed. Closing this issue, as the general sentiment is that heal rods aren't an issue with the delay.
