### ISSUE TITLE
Remove Curse potions in every town

### ISSUE THREAD

**Issue by amenius** [Daenks/Meridian59_103#451]
Cursed items are a very time consuming building-stopper. When you accidentally pick up a cursed weapon building in CV, you have to run all the way to Marion and back to be able to continue building. Even worse - when fighting trees or frogmen, you MUST have a mule to help out.

Thus, I would recommend to remove the Karma requirements on remove curse potions and let all innkeepers sell them. This way, you still should take care of what you pick up, but you cannot be crippled as badly as now.

What do you think?

**Comment by skittles1** [comment]
Karma requirement removed and the potions are now sold by Frisconar and Zala on island.
